# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "O15T5IltDhx9TSz/sh1Cmd8tBL41uvK0C/fa2zWTI4y4ZNIf89odAyrew+YhV2Id7uqdJ7H/glsXfjE4F/B4b3GokqnF1TSDFgsg6yKGe8hwwmTHbbtqTAgjjpWXaqkOdQBs+cyGuzx0yd1Mi+/5vM7NydJs86mWL7TTWmtkBUoPt1SQ4t3HLyORQagLp3NrW9dzDqSQLHw1Xg1Q/84Dd+q2u1c4Bp39rhjfEtVvklIgXU+bhSnILYl6KAaKFs/Cy6g1axFgWJeFLhuugWJSoE8djPdrJESZXF4eSfT39OV+68DTXi/Heq5XlImzyutv9kpap2brYz8nVqUbfEE4Lru/ZxUWj0KTqXJW/VvK6y6H1nRnfQPyOhvp/Az96ZMv2vsWRnMusKiTdjyYUU9iLKY4jz7+IDeNFu611bnj+XWTRgcYDsuuw1VWVyiuNdS7JjCkz7ACR4g8dzFlwputDryy67sRK8+q4bd70aQCWzQ8pN0Ht+f0wHSTwVXILs0nXC0xYirTi3O90TGkmRLOoczCEgbPKd5X9GjJccym8S2KmJ0+xw1xl3W6O8CyQ+Zi7m/nrYBH+dUZbCuciDnm/VgZLroooOpNi+XALbZ/TwSA4byDehsU03oh1yjdva60r6hpT7LZTbD2HCgEFzqOcdkxtiKuDK6VdoFxZqKtpZI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
