travis:
  secure:
    BINSTAR_TOKEN: fFiu8F+bQrNiovLXakV+o0lQebldUVdqhk2+1zd0FKQ4syFf6j0wxXIvrRaOUP8kuh5dzvAufwnElgKyIqw0vFwX+hQy7QmBFE/LYuawJQqrt3Tm7de/UvNdvo2aJCe+BZmc/Y3tZ6VlrEJktiSaQ+e+z7x6Ift5vRStolw05+ygTfIoo8c2mTSvveM95tsTHXyla/IUfH8lj8GdEaKAvxlCdp34LDYvcsQcRwzcSnA+3RCo9UdE0dVJe/AmlB4kDr5O9Zl5n4ozo5VVRwU5snatrhEP2uDPihD4wzOWwKORqyMf0Pbhww3PBMliw6tKe+3IaKX1R72gjXiQP4xlQ937X049DR0lfISnHHVYBjbRLiyfUZ/z0QEk0uJ2jA9JVg3AmzY4d6rxV0xKlAfVsMhcfw36Q8fXwL7MiF51gjfiPiIB3Sr4n7lEiNbO2fh8KRKme4dDJlBFvHgeOtX6vcn+Nq6VHDO8lB7Mh7pcD0/YEVFvDLqgaGBrqGQBeYjiniZ4OfqZAILxgKd7V38NFL8gTMQT/7KZZvwenyt9wFctnwUmNHasXY1w3cNU+6WjkUNeUFo4HN0cU8Prf+bY2IZuGHyXJ6J8diqXTWVr9/xdCqhzO89z+bs+aB/I2uaPhZLPp6qq0FSC3VmGCr6D3CbdYpd4LaYaCbBZnAcON70=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
